import 'package:flutter/material.dart';

class SystemModel {
  final String name;
  final String manufacturer;
  final int releaseYear;
  final String sourceSlug;
  final List<String>? sourceSlugs;
  final String esdeFolder;
  final List<String> extensions;
  final bool isZipped;
  final String libretroId;
  final double gridRatio;
  final List<String> romExtensions;
  final String iconName;
  final Color accentColor;
  final List<String>? multiFileExtensions;

  const SystemModel({
    required this.name,
    required this.manufacturer,
    required this.releaseYear,
    required this.sourceSlug,
    this.sourceSlugs,
    required this.esdeFolder,
    required this.extensions,
    this.isZipped = true,
    this.libretroId = '',
    this.gridRatio = 0.7,
    this.romExtensions = const [],
    this.iconName = '',
    this.accentColor = Colors.redAccent,
    this.multiFileExtensions,
  });

  /// Returns the local asset path for this system's icon.
  String get iconAssetPath => 'assets/platform_icons/$iconName';

  static const List<SystemModel> supportedSystems = [
    // ===== NINTENDO =====
    SystemModel(
      name: 'Nintendo Entertainment System',
      manufacturer: 'Nintendo',
      releaseYear: 1983,
      sourceSlug:
          'No-Intro/Nintendo - Nintendo Entertainment System (Headered)',
      esdeFolder: 'nes',
      extensions: ['.zip', '.nes'],
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_Entertainment_System',
      gridRatio: 0.71,
      romExtensions: ['.nes'],
      iconName: 'NES.png',
      accentColor: Color(0xFFE11D48),
    ),
    SystemModel(
      name: 'Super Nintendo',
      manufacturer: 'Nintendo',
      releaseYear: 1990,
      sourceSlug: 'No-Intro/Nintendo - Super Nintendo Entertainment System',
      esdeFolder: 'snes',
      extensions: ['.zip', '.sfc'],
      isZipped: true,
      libretroId: 'Nintendo_-_Super_Nintendo_Entertainment_System',
      gridRatio: 0.7,
      romExtensions: ['.sfc'],
      iconName: 'SNES.png',
      accentColor: Color(0xFF9333EA),
    ),
    SystemModel(
      name: 'Nintendo 64',
      manufacturer: 'Nintendo',
      releaseYear: 1996,
      sourceSlug: 'No-Intro/Nintendo - Nintendo 64 (BigEndian)',
      esdeFolder: 'n64',
      extensions: ['.zip', '.z64', '.n64'],
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_64',
      gridRatio: 1.5,
      romExtensions: ['.z64', '.n64'],
      iconName: 'N64.png',
      accentColor: Color(0xFFF97316),
    ),
    SystemModel(
      name: 'Nintendo GameCube',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      sourceSlug: 'Redump/Nintendo - GameCube - NKit RVZ [zstd-19-128k]',
      esdeFolder: 'gc',
      extensions: ['.rvz'],
      isZipped: false,
      libretroId: 'Nintendo_-_GameCube',
      gridRatio: 0.71,
      romExtensions: ['.rvz'],
      iconName: 'GAMECUBE.png',
      accentColor: Color(0xFF7C3AED),
    ),
    SystemModel(
      name: 'Nintendo Wii',
      manufacturer: 'Nintendo',
      releaseYear: 2006,
      sourceSlug: 'Redump/Nintendo - Wii - NKit RVZ [zstd-19-128k]',
      esdeFolder: 'wii',
      extensions: ['.rvz'],
      isZipped: false,
      libretroId: 'Nintendo_-_Wii',
      gridRatio: 0.71,
      romExtensions: ['.rvz'],
      iconName: 'Wii.png',
      accentColor: Color(0xFF0EA5E9),
    ),
    SystemModel(
      name: 'Game Boy',
      manufacturer: 'Nintendo',
      releaseYear: 1989,
      sourceSlug: 'No-Intro/Nintendo - Game Boy',
      esdeFolder: 'gb',
      extensions: ['.zip', '.gb'],
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy',
      gridRatio: 1.0,
      romExtensions: ['.gb'],
      iconName: 'Game_Boy.png',
      accentColor: Color(0xFF8BAC0F),
    ),
    SystemModel(
      name: 'Game Boy Color',
      manufacturer: 'Nintendo',
      releaseYear: 1998,
      sourceSlug: 'No-Intro/Nintendo - Game Boy Color',
      esdeFolder: 'gbc',
      extensions: ['.zip', '.gbc'],
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Color',
      gridRatio: 1.0,
      romExtensions: ['.gbc'],
      iconName: 'Game_Boy_Color.png',
      accentColor: Color(0xFF7C3AED),
    ),
    SystemModel(
      name: 'Game Boy Advance',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      sourceSlug: 'No-Intro/Nintendo - Game Boy Advance',
      esdeFolder: 'gba',
      extensions: ['.zip', '.gba'],
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Advance',
      gridRatio: 1.0,
      romExtensions: ['.gba'],
      iconName: 'Game_Boy_Advance.png',
      accentColor: Color(0xFF4F46E5),
    ),
    SystemModel(
      name: 'Nintendo DS',
      manufacturer: 'Nintendo',
      releaseYear: 2004,
      sourceSlug: 'No-Intro/Nintendo - Nintendo DS (Decrypted)',
      esdeFolder: 'nds',
      extensions: ['.zip', '.nds'],
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_DS',
      gridRatio: 1.15,
      romExtensions: ['.nds'],
      iconName: 'NINTENDO_DS.png',
      accentColor: Color(0xFF6B7280),
    ),
    SystemModel(
      name: 'Nintendo 3DS',
      manufacturer: 'Nintendo',
      releaseYear: 2011,
      sourceSlug: 'No-Intro/Nintendo - Nintendo 3DS (Decrypted)',
      esdeFolder: 'n3ds',
      extensions: ['.3ds', '.cia'],
      isZipped: false,
      libretroId: 'Nintendo_-_Nintendo_3DS',
      gridRatio: 1.10,
      romExtensions: ['.3ds', '.cia'],
      iconName: 'NINTENDO_3DS.png',
      accentColor: Color(0xFFDC2626),
    ),
    // ===== SONY =====
    SystemModel(
      name: 'PlayStation',
      manufacturer: 'Sony',
      releaseYear: 1994,
      sourceSlug: 'Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA',
      sourceSlugs: [
        'Internet%20Archive/chadmaster/chd_psx/CHD-PSX-Improvements',
        'Internet%20Archive/chadmaster/chd_psx/CHD-PSX-USA',
        'Internet%20Archive/chadmaster/chd_psx_eur/CHD-PSX-EUR',
        'Internet%20Archive/chadmaster/chd_psx_jap/CHD-PSX-JAP',
        'Internet%20Archive/chadmaster/chd_psx_jap_p2/CHD-PSX-JAP',
        'Internet%20Archive/chadmaster/chd_psx_misc/CHD-PSX-Misc',
      ],
      esdeFolder: 'psx',
      extensions: ['.chd', '.pbp', '.cue', '.zip'],
      isZipped: false,
      libretroId: 'Sony_-_PlayStation',
      gridRatio: 1.0,
      romExtensions: ['.chd', '.pbp', '.cue'],
      iconName: 'PS1.png',
      accentColor: Color(0xFF5B21B6),
      multiFileExtensions: ['.bin', '.cue'],
    ),
    SystemModel(
      name: 'PlayStation 2',
      manufacturer: 'Sony',
      releaseYear: 2000,
      sourceSlug: 'Redump/Sony - PlayStation 2',
      esdeFolder: 'ps2',
      extensions: ['.iso', '.chd', '.zip'],
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_2',
      gridRatio: 0.71,
      romExtensions: ['.iso', '.chd'],
      iconName: 'PS2.png',
      accentColor: Color(0xFF1E3A8A),
      multiFileExtensions: ['.bin', '.cue'],
    ),
    SystemModel(
      name: 'PlayStation Portable',
      manufacturer: 'Sony',
      releaseYear: 2004,
      sourceSlug: 'Redump/Sony - PlayStation Portable',
      esdeFolder: 'psp',
      extensions: ['.iso', '.cso'],
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_Portable',
      gridRatio: 0.6,
      romExtensions: ['.iso', '.cso'],
      iconName: 'PSP.png',
      accentColor: Color(0xFF111827),
    ),
    // ===== SEGA =====
    SystemModel(
      name: 'Master System',
      manufacturer: 'Sega',
      releaseYear: 1985,
      sourceSlug: 'No-Intro/Sega - Master System - Mark III',
      esdeFolder: 'mastersystem',
      extensions: ['.zip', '.sms'],
      isZipped: true,
      libretroId: 'Sega_-_Master_System_-_Mark_III',
      gridRatio: 0.71,
      romExtensions: ['.sms'],
      iconName: 'GENESIS.png',
      accentColor: Color(0xFF1D4ED8),
    ),
    SystemModel(
      name: 'Mega Drive',
      manufacturer: 'Sega',
      releaseYear: 1988,
      sourceSlug: 'No-Intro/Sega - Mega Drive - Genesis',
      esdeFolder: 'megadrive',
      extensions: ['.zip', '.md', '.gen'],
      isZipped: true,
      libretroId: 'Sega_-_Mega_Drive_-_Genesis',
      gridRatio: 0.71,
      romExtensions: ['.md', '.gen'],
      iconName: 'GENESIS.png',
      accentColor: Color(0xFF111827),
    ),
    SystemModel(
      name: 'Game Gear',
      manufacturer: 'Sega',
      releaseYear: 1990,
      sourceSlug: 'No-Intro/Sega - Game Gear',
      esdeFolder: 'gamegear',
      extensions: ['.zip', '.gg'],
      isZipped: true,
      libretroId: 'Sega_-_Game_Gear',
      gridRatio: 0.71,
      romExtensions: ['.gg'],
      iconName: 'GAME_GEAR.png',
      accentColor: Color(0xFF0F766E),
    ),
    SystemModel(
      name: 'Dreamcast',
      manufacturer: 'Sega',
      releaseYear: 1998,
      sourceSlug:
          'Internet%20Archive/chadmaster/dc-chd-zstd-redump/dc-chd-zstd/',
      esdeFolder: 'dreamcast',
      extensions: ['.chd'],
      isZipped: false,
      libretroId: 'Sega_-_Dreamcast',
      gridRatio: 1.0,
      romExtensions: ['.chd'],
      iconName: 'Dreamcast.png',
      accentColor: Color(0xFFDC2626),
    ),
    SystemModel(
      name: 'Saturn',
      manufacturer: 'Sega',
      releaseYear: 1994,
      sourceSlug: 'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/USA',
      sourceSlugs: [
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/USA',
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/Europe',
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/Japan',
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/Improvements',
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/Translations',
        'Internet%20Archive/chadmaster/chd_saturn/CHD-Saturn/Other-Regions',
      ],
      esdeFolder: 'saturn',
      extensions: ['.chd', '.cue', '.zip'],
      isZipped: false,
      libretroId: 'Sega_-_Saturn',
      gridRatio: 1.0,
      romExtensions: ['.chd', '.cue'],
      iconName: 'SATURN.png',
      accentColor: Color(0xFF7C3AED),
      multiFileExtensions: ['.bin', '.cue'],
    ),
  ];
}
