import 'package:flutter/material.dart';

class SystemModel {
  final String id;
  final String name;
  final String manufacturer;
  final int releaseYear;
  final bool isZipped;
  final String libretroId;
  final List<String> romExtensions;
  final String iconName;
  final Color accentColor;
  final List<String>? multiFileExtensions;

  const SystemModel({
    required this.id,
    required this.name,
    required this.manufacturer,
    required this.releaseYear,
    this.isZipped = true,
    this.libretroId = '',
    this.romExtensions = const [],
    this.iconName = '',
    this.accentColor = Colors.redAccent,
    this.multiFileExtensions,
  });

  /// Returns the local asset path for this system's icon.
  String get iconAssetPath => 'assets/platform_icons/$iconName';

  static const List<SystemModel> supportedSystems = [
    // ===== NINTENDO =====
    SystemModel(
      id: 'nes',
      name: 'Nintendo Entertainment System',
      manufacturer: 'Nintendo',
      releaseYear: 1983,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_Entertainment_System',
      romExtensions: ['.nes'],
      iconName: 'NES.png',
      accentColor: Color(0xFFE11D48),
    ),
    SystemModel(
      id: 'snes',
      name: 'Super Nintendo',
      manufacturer: 'Nintendo',
      releaseYear: 1990,
      isZipped: true,
      libretroId: 'Nintendo_-_Super_Nintendo_Entertainment_System',
      romExtensions: ['.sfc'],
      iconName: 'SNES.png',
      accentColor: Color(0xFF9333EA),
    ),
    SystemModel(
      id: 'n64',
      name: 'Nintendo 64',
      manufacturer: 'Nintendo',
      releaseYear: 1996,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_64',
      romExtensions: ['.z64', '.n64'],
      iconName: 'N64.png',
      accentColor: Color(0xFFF97316),
    ),
    SystemModel(
      id: 'gc',
      name: 'Nintendo GameCube',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      isZipped: false,
      libretroId: 'Nintendo_-_GameCube',
      romExtensions: ['.rvz'],
      iconName: 'GAMECUBE.png',
      accentColor: Color(0xFF7C3AED),
    ),
    SystemModel(
      id: 'wii',
      name: 'Nintendo Wii',
      manufacturer: 'Nintendo',
      releaseYear: 2006,
      isZipped: false,
      libretroId: 'Nintendo_-_Wii',
      romExtensions: ['.rvz'],
      iconName: 'Wii.png',
      accentColor: Color(0xFF0EA5E9),
    ),
    SystemModel(
      id: 'wiiu',
      name: 'Nintendo Wii U',
      manufacturer: 'Nintendo',
      releaseYear: 2012,
      isZipped: false,
      libretroId: 'Nintendo_-_Wii_U',
      romExtensions: ['.wua', '.wud', '.wux', '.rpx'],
      iconName: 'Wii_U.png',
      accentColor: Color(0xFF0284C7),
    ),
    SystemModel(
      id: 'switch',
      name: 'Nintendo Switch',
      manufacturer: 'Nintendo',
      releaseYear: 2017,
      isZipped: false,
      libretroId: 'Nintendo_-_Switch',
      romExtensions: ['.nsp', '.xci'],
      iconName: 'Switch.png',
      accentColor: Color(0xFFE60012),
    ),
    SystemModel(
      id: 'gb',
      name: 'Game Boy',
      manufacturer: 'Nintendo',
      releaseYear: 1989,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy',
      romExtensions: ['.gb'],
      iconName: 'Game_Boy.png',
      accentColor: Color(0xFF8BAC0F),
    ),
    SystemModel(
      id: 'gbc',
      name: 'Game Boy Color',
      manufacturer: 'Nintendo',
      releaseYear: 1998,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Color',
      romExtensions: ['.gbc'],
      iconName: 'Game_Boy_Color.png',
      accentColor: Color(0xFF7C3AED),
    ),
    SystemModel(
      id: 'gba',
      name: 'Game Boy Advance',
      manufacturer: 'Nintendo',
      releaseYear: 2001,
      isZipped: true,
      libretroId: 'Nintendo_-_Game_Boy_Advance',
      romExtensions: ['.gba'],
      iconName: 'Game_Boy_Advance.png',
      accentColor: Color(0xFF4F46E5),
    ),
    SystemModel(
      id: 'nds',
      name: 'Nintendo DS',
      manufacturer: 'Nintendo',
      releaseYear: 2004,
      isZipped: true,
      libretroId: 'Nintendo_-_Nintendo_DS',
      romExtensions: ['.nds'],
      iconName: 'NINTENDO_DS.png',
      accentColor: Color(0xFF6B7280),
    ),
    SystemModel(
      id: 'n3ds',
      name: 'Nintendo 3DS',
      manufacturer: 'Nintendo',
      releaseYear: 2011,
      isZipped: false,
      libretroId: 'Nintendo_-_Nintendo_3DS',
      romExtensions: ['.3ds', '.cia'],
      iconName: 'NINTENDO_3DS.png',
      accentColor: Color(0xFFDC2626),
    ),
    // ===== SONY =====
    SystemModel(
      id: 'psx',
      name: 'PlayStation',
      manufacturer: 'Sony',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation',
      romExtensions: ['.chd', '.pbp', '.cue'],
      iconName: 'PS1.png',
      accentColor: Color(0xFF5B21B6),
      multiFileExtensions: ['.bin', '.cue'],
    ),
    SystemModel(
      id: 'ps2',
      name: 'PlayStation 2',
      manufacturer: 'Sony',
      releaseYear: 2000,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_2',
      romExtensions: ['.iso', '.chd'],
      iconName: 'PS2.png',
      accentColor: Color(0xFF1E3A8A),
      multiFileExtensions: ['.bin', '.cue'],
    ),
    SystemModel(
      id: 'ps3',
      name: 'PlayStation 3',
      manufacturer: 'Sony',
      releaseYear: 2006,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_3',
      romExtensions: ['.iso'],
      iconName: 'PS3.png',
      accentColor: Color(0xFF1E293B),
    ),
    SystemModel(
      id: 'ps4',
      name: 'PlayStation 4',
      manufacturer: 'Sony',
      releaseYear: 2013,
      isZipped: false,
      libretroId: '',
      romExtensions: ['.pkg'],
      iconName: 'PS4.png',
      accentColor: Color(0xFF1D4ED8),
    ),
    SystemModel(
      id: 'psp',
      name: 'PlayStation Portable',
      manufacturer: 'Sony',
      releaseYear: 2004,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_Portable',
      romExtensions: ['.iso', '.cso'],
      iconName: 'PSP.png',
      accentColor: Color(0xFF111827),
    ),
    SystemModel(
      id: 'psvita',
      name: 'PlayStation Vita',
      manufacturer: 'Sony',
      releaseYear: 2011,
      isZipped: false,
      libretroId: 'Sony_-_PlayStation_Vita',
      romExtensions: ['.vpk'],
      iconName: 'PS_VITA.png',
      accentColor: Color(0xFF1E40AF),
    ),
    // ===== SEGA =====
    SystemModel(
      id: 'mastersystem',
      name: 'Master System',
      manufacturer: 'Sega',
      releaseYear: 1985,
      isZipped: true,
      libretroId: 'Sega_-_Master_System_-_Mark_III',
      romExtensions: ['.sms'],
      iconName: 'GENESIS.png',
      accentColor: Color(0xFF1D4ED8),
    ),
    SystemModel(
      id: 'megadrive',
      name: 'Mega Drive',
      manufacturer: 'Sega',
      releaseYear: 1988,
      isZipped: true,
      libretroId: 'Sega_-_Mega_Drive_-_Genesis',
      romExtensions: ['.md', '.gen'],
      iconName: 'GENESIS.png',
      accentColor: Color(0xFF111827),
    ),
    SystemModel(
      id: 'gamegear',
      name: 'Game Gear',
      manufacturer: 'Sega',
      releaseYear: 1990,
      isZipped: true,
      libretroId: 'Sega_-_Game_Gear',
      romExtensions: ['.gg'],
      iconName: 'GAME_GEAR.png',
      accentColor: Color(0xFF0F766E),
    ),
    SystemModel(
      id: 'dreamcast',
      name: 'Dreamcast',
      manufacturer: 'Sega',
      releaseYear: 1998,
      isZipped: false,
      libretroId: 'Sega_-_Dreamcast',
      romExtensions: ['.chd'],
      iconName: 'Dreamcast.png',
      accentColor: Color(0xFFDC2626),
    ),
    SystemModel(
      id: 'saturn',
      name: 'Saturn',
      manufacturer: 'Sega',
      releaseYear: 1994,
      isZipped: false,
      libretroId: 'Sega_-_Saturn',
      romExtensions: ['.chd', '.cue'],
      iconName: 'SATURN.png',
      accentColor: Color(0xFF7C3AED),
      multiFileExtensions: ['.bin', '.cue'],
    ),
    // ===== SNK =====
    SystemModel(
      id: 'ngpc',
      name: 'Neo Geo Pocket Color',
      manufacturer: 'SNK',
      releaseYear: 1999,
      isZipped: true,
      libretroId: 'SNK_-_Neo_Geo_Pocket_Color',
      romExtensions: ['.ngc', '.ngp'],
      iconName: 'Neo_Geo_Pocket_Color.png',
      accentColor: Color(0xFF4338CA),
    ),
    // ===== ARCADE =====
    SystemModel(
      id: 'arcade',
      name: 'Arcade',
      manufacturer: 'Various',
      releaseYear: 1978,
      isZipped: false,
      libretroId: 'MAME',
      romExtensions: ['.zip'],
      iconName: 'Arcade.png',
      accentColor: Color(0xFFD97706),
    ),
    // ===== MICROSOFT =====
    SystemModel(
      id: 'xbox',
      name: 'Xbox',
      manufacturer: 'Microsoft',
      releaseYear: 2001,
      isZipped: false,
      libretroId: 'Microsoft_-_Xbox',
      romExtensions: ['.iso'],
      iconName: 'Xbox.png',
      accentColor: Color(0xFF16A34A),
    ),
    SystemModel(
      id: 'xbox360',
      name: 'Xbox 360',
      manufacturer: 'Microsoft',
      releaseYear: 2005,
      isZipped: false,
      libretroId: '',
      romExtensions: ['.iso', '.xex'],
      iconName: 'Xbox_360.png',
      accentColor: Color(0xFF65A30D),
    ),
  ];
}
